margin=120
always_for_in=true
remove_extra_newlines=true
long_to_short_function_def=true
always_use_return=true
format_docstrings=true
indent_submodule=true
format_markdown=true
ignore = [
    "README.md", 
    "CODE_OF_CONDUCT.md"
]