name: Run benchmarks

on:
  push:
    branches:
      - master

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1'

      - name: Install dependencies
        run: |
          julia -e 'using Pkg; Pkg.add("PkgBenchmark")'
          julia -e 'using Pkg; Pkg.instantiate()'

      - name: Run benchmarks
        run: julia -e 'using PkgBenchmark; result = benchmarkpkg("QuPhys"); PkgBenchmark.export_markdown("benchmark/results.md", result)'

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add benchmark/results.md
          git commit -m "Update benchmark results"
          git push
